FROM bitnami/minideb:latest

## to download the most recent version from gunthy.org (full package) => we just need the node_modules folder ...
ARG INSTALL_URL_FULL="https://gunthy.org/downloads/gunthy_linux.zip"
ARG INSTALL_URL_MONITOR="https://gunthy.org/downloads/monit-linux.zip"
ARG DEBIAN_FRONTEND=noninteractive
ARG VCS_REF
LABEL org.label-schema.vcs-ref=$VCS_REF org.label-schema.vcs-url="https://github.com/robbatt/docker-gunbot"

## Setup Enviroment
ENV TZ=Europe/Berlin \
TERM=xterm-256color \
FORCE_COLOR=true \
NPM_CONFIG_COLOR=always \
MOCHA_COLORS=true \
INSTALL_URL_FULL=${INSTALL_URL_FULL} \
INSTALL_URL_MONITOR=${INSTALL_URL_MONITOR} \

## Setup pre-requisites
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get -y update && \
 apt-get install -y apt-utils

## Install additional libraries and upgrade
RUN apt-get -y upgrade && \
 apt-get install -y unzip curl fontconfig fonts-dejavu-extra ca-certificates && \
 apt-get clean -y && \
 apt-get autoclean -y && \
 apt-get autoremove -y

RUN update-ca-certificates --fresh

RUN fc-cache -fv

## Download Gunbot Full Package
WORKDIR /tmp
RUN curl -Lo /tmp/lin.zip ${INSTALL_URL_FULL}

RUN unzip -q lin.zip \
 && rm lin.zip \
 && mkdir -p /gunbot \
 && mv node_modules /gunbot \
 && rm -rf *

RUN curl -Lo /tmp/mon.zip ${INSTALL_URL_MONITOR}
RUN unzip -q mon.zip \
 && rm mon.zip \
 && mv monit-linux /gunbot/ \
 && chmod +x /gunbot/monit-linux

WORKDIR /gunbot

EXPOSE 5000

CMD /gunbot/monit-linux
